### ISSUE TITLE
Validate deletion policy when its value is taken form a parameter

### ISSUE THREAD

**Issue by pfigwer** [Appliscale/perun#113]
Problem is well described in the following article:
https://www.unixdaemon.net/cloud/cloudformation-annoyance-deletion-policy-parameters/.

**Comment by maxiwoj** [comment]
deletion policy still valid only when passed as a string literal only. Either we apply for the AWS rules and validate deletion policy same as AWS or provide our own mechanizm for setting this from command line - this could be a nice feature, but maybe a not necessary one - AWS policy can change any time (unlikely, since this has already been reported as a feature request a few years ago, but still..)

**Comment by pfigwer** [comment]
Let's go with simplest way - validate deletion policy same as AWS and return message with comprehensive description why it is not valid.
