### ISSUE TITLE
Validation - Improvements

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#37]
After releasing `1.0.0` we would like introduce couple of improvements `1.1.0`:

- We are stopping after finding a first error.
- We are missing line and column when listing errors.
- `validate_offline` is a pretty long name - how about `lint` or `check`?

**Comment by afronski** [comment]
This task handles also _JSON parser_ improvements.

**Comment by afronski** [comment]
@jlampar Please handle from now on integration for new _JSON_ parser that @amamla provided.

**Comment by jlampar** [comment]
Integration of the parser wasn't done yet because of the complexity of the issue. The only thing finished in #88 was using the `lineAndCharacter` function from the new parser to detect the line and column of the JSON error. The function lives now in the `offlinevalidator.go` body and would be eventually removed and imported if we would decide do use the new parser for the template elements analysis. At the moment it collaborates with the built-in `json` library in detecting the exact position of the error.

For example, this JSON:

```
{
  "Mappings" : {
    "RegionMap" : {
      "us-east-1" : { "32" : "ami-6411e20d", "64" : "ami-7a11e213" },
      "us-west-1" : { "32" : "ami-c9c7978c", "64" : "ami-cfc7978a" },
      "eu-west-1" : { "32" : "ami-37c2f643", "64" : "ami-31c2f645" },
      "ap-southeast-1" : { "32" : "ami-66f28c34", "64" : "ami-60f28c32" },
      "ap-northeast-1" : { "32" : "ami-9c03a89d", "64" : "ami-a003a8a1" }
    }
  },

  "Resources" : {
    "myEC2Instance"  {
      "Type" : "AWS::EC2::Instance",
      "Properties" : {
        "ImageId" : { "Fn::FindInMap" : [ "RegionMap", { "Ref" : "AWS::Region" }, "32"]},
        "InstanceType" : "m1.small"
      }
    }
  }
}
```

Would output the following ERROR:

```
ERROR: Syntax error at line 13, column 22
ERROR: invalid character '{' after object key
ERROR: Template is invalid!
```
